name: soal_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  flutter_colorpicker: ^1.0.3
  open_file: ^3.2.1
  file_picker: ^5.2.6
  provider: ^6.0.5
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  shared_preferences: ^2.1.0
  sqflite: ^2.2.6
  path: ^1.8.2
  path_provider: ^2.0.14
  dio: ^5.1.1
  flutter_speed_dial: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.3.3

dependency_overrides:
  ffi: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
